Add .NET implementation
wulkanowy/qr pull request #6
Opened 2020-11-25 09:26 UTC by MRmlik12

2020-11-25 13:13 UTC, mklkj requested changes

2020-11-25 13:13 UTC, mklkj commented on dotnet/WulkanowyQr.Test/QrTest.cs
> +        private const string _base64 = "pDXpCcBDr7/wssR2YJpdaB+BXPJD5I28epToqZ1bO5O8qUTBru7NVAm9Rf3lDUr3RKAmoXKm5D96TnTI1yfUzQ==";
Użyj zamiast tego tych samych danych testowych co w testach pozostałych implementacji, tj. https://github.com/wulkanowy/qr/blob/master/php/tests/ConverterTest.php#L9-L11

2020-11-25 13:13 UTC, mklkj commented on dotnet/WulkanowyQr/Qr.cs
> +namespace WulkanowyQr
Użyj proszę tego samego namespace'a co w uonet-request-signerze https://github.com/wulkanowy/uonet-request-signer/blob/master/dotnet/UonetRequestSigner/UonetRequestSigner.cs#L10

2020-11-25 13:13 UTC, mklkj commented on dotnet/WulkanowyQr/Qr.cs
> +}
\n

2020-11-25 13:13 UTC, mklkj commented on dotnet/WulkanowyQr.Example/Program.cs
> +            var encode = Qr.Encode("ABCDEFG", "CODE");
Dla spójności tutaj użyj tych samych danych co w przykładzie przy impl w dartcie https://github.com/wulkanowy/qr/blob/master/dart/example/uonet_qr_example.dart#L5

2020-11-25 13:13 UTC, mklkj commented on dotnet/README.md
> +```csharp
Ten przykład użycia można byłoby trochę uprościć, zostawiając dosłownie tylko tyle, ile trzeba dodać do swojego kodu, a nie pełny kompilowalny przykład (ten jest w dotnet/WulkanowyQr.Example/Program.cs), coś bardziej jak https://github.com/wulkanowy/uonet-request-signer/blob/master/dotnet/README.md#usage

2020-11-25 14:06 UTC, MRmlik12 commented
Chyba teraz powinno być dobrze

2020-11-29 23:44 UTC, mklkj commented
@MRmlik12 dodaj jeszcze do configu circleci odpalanie testów, podobnie jak tutaj https://github.com/wulkanowy/uonet-request-signer/blob/master/.circleci/config.yml#L69-L77

2020-11-30 08:23 UTC, MRmlik12 commented
Myślę, że ten config jest dobrze zrobiony

2020-11-30 10:02 UTC, mklkj commented
Był mały błąd w ustawieniach na circleci i przez to nie uruchamiał się build w PRach z forków. @MRmlik12 wrzuć proszę jakiś commit (może być pusty), który striggeruje build. Zmerguję jak testy przejdą

2020-11-30 10:45 UTC, MRmlik12 commented
Zmieniłem tylko główny plik README.md, aby mógł wysłać

2020-11-30 10:46 UTC, mklkj approved these changes

2020-11-30 10:49 UTC, merged